[project]
name = "agentic-ai-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "openai-agents>=0.0.17",
    "pydantic>=2.11.5",
    "python-decouple>=3.8",
]
